distributed_backend: "nccl"
num_cpu_workers: 6

# Data
data_path: "LI-Small_Trans.csv"
k_neighborhood_transactions: 30
train_split_ratio: 0.8

# Model Architecture
account_embedding_dim: 256
transaction_embedding_dim: 128
gnn_hidden_dim: 256
gnn_layers: 3
model_output_classes: 1

# Training
epochs: 5
batch_size_per_gpu: 256
learning_rate: 0.0001
weight_decay: 0.0001
print_interval_batches: 1000
pos_weight_enabled: true
gradient_accumulation_steps: 1

# Visualization
visualization_enabled: true
plot_threshold: 0.8


# loss Focal/BCE
loss:
  type: "FocalLoss"
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2
